Refactor BaseChildImmunization class
OpenSRP/opensrp-client-child pull request #179
Opened 2020-09-08 09:00 UTC by ndegwamartin

- Refactor for testability and maintainability

2020-09-11 16:55 UTC, ekigamba requested changes

2020-09-14 08:33 UTC, ekigamba requested changes

2020-09-14 08:33 UTC, ekigamba commented on opensrp-child/src/main/java/org/smartregister/child/contract/ChildImmunizationContract.java
> +        String getString(int updating_dialog_title);
Fix variable naming here

2020-09-14 08:38 UTC, ndegwamartin commented on opensrp-child/src/main/java/org/smartregister/child/util/ChildDbUtils.java
> +            commonPersonObjectClient = new CommonPersonObjectClient(baseEntityId, childDetails, Constants.KEY.CHILD);
This is meant to be the entity name e.g. mother, father e.t.c

2020-09-14 09:20 UTC, ndegwamartin commented on opensrp-child/src/test/java/org/smartregister/child/presenter/BaseChildImmunizationPresenterTest.java
> +        Assert.assertEquals(5, heightList.size());
Done

2020-09-14 09:20 UTC, ndegwamartin commented on opensrp-child/src/main/java/org/smartregister/child/contract/ChildImmunizationContract.java
> +        String getString(int updating_dialog_title);
Done

2020-09-14 11:56 UTC, ekigamba approved these changes

2020-09-14 12:02 UTC, merged