test SaveAdverseEventTask
OpenSRP/opensrp-client-child pull request #180
Opened 2020-09-08 09:09 UTC by Andati

2020-09-11 08:01 UTC, ekigamba requested changes

2020-09-11 08:01 UTC, ekigamba commented on opensrp-child/src/test/java/org/smartregister/child/task/SaveAdverseEventTaskTest.java
> +        assertEquals("loc-123", argument2.getValue().getString("childLocationId"));
I think we can verify other properties such as the following

- baseEntityId
- eventDate
- eventType
- locationId
- providerId
- entityType
- formSubmissionId

- 2 obs

- all metadata 

To make sure breaking changes are easily caught. Once this is merged, this method will be assumed to have test coverage irrespective of the number of things verified. I therefore think it would be nice to cover this in this PR. What do you think?

2020-09-11 08:01 UTC, ekigamba commented on opensrp-child/src/main/java/org/smartregister/child/task/SaveAdverseEventTask.java
>                  String value = ChildJsonFormUtils.getString(jsonObject, ChildJsonFormUtils.VALUE);
I am not sure aboutt this specific use-case but I think obs can use the `values` instead of `value` to store the saved value. How does this work?

2020-09-29 08:44 UTC, Andati commented on opensrp-child/src/main/java/org/smartregister/child/task/SaveAdverseEventTask.java
>                  String value = ChildJsonFormUtils.getString(jsonObject, ChildJsonFormUtils.VALUE);
it's currently using `values`

2020-09-30 14:32 UTC, ekigamba approved these changes

2020-09-30 14:34 UTC, merged