Customizations for UNICEF Angola
OpenSRP/opensrp-client-child pull request #203
Opened 2020-11-05 06:05 UTC by hamza-vd

If the parameter vaccine.overdue.status.hide is set to true then due and over due statuses colors will be white. No indication will be shown for these statuses.

2020-11-13 06:50 UTC, ellykits requested changes

2020-11-13 06:50 UTC, ellykits commented on opensrp-child/src/main/java/org/smartregister/child/task/VaccinationAsyncTask.java
> +    private boolean hideOverdueVaccine = ChildLibrary.getInstance().getProperties().hasProperty(ChildAppProperties.KEY.VACCINE_OVERDUE_STATUS_HIDE) && ChildLibrary.getInstance().getProperties().getPr
Change this to **hideOverdueVaccineStatus**

2020-11-13 06:50 UTC, ellykits commented on opensrp-child/src/main/java/org/smartregister/child/util/ChildAppProperties.java
> +        public static final String VACCINE_OVERDUE_STATUS_HIDE = "vaccine.overdue.status.hide";
Rename to **HIDE_OVERDUE_VACCINE_STATUS = "hide.overdue.vaccine.status"**

2020-11-13 06:50 UTC, ellykits commented on sample/src/main/assets/app.properties
> +vaccine.overdue.status.hide=false
Question is this necessary if this is the default behavior? 
Remember to update to this **hide.overdue.vaccine.status**

2020-11-13 06:52 UTC, ellykits commented
Also remember to update your branch with master and add library version on **gradle.properties** file

2020-11-13 07:02 UTC, hamza-vd commented on sample/src/main/assets/app.properties
> +vaccine.overdue.status.hide=false
Yes  `vaccine.overdue.status.hide` will be false by default if it isn't declared here. I have declared it just for the reference. Should I remove it?

2020-11-13 07:38 UTC, ellykits commented on sample/src/main/assets/app.properties
> +vaccine.overdue.status.hide=false
Remove if not necessary

2020-12-04 15:19 UTC, ellykits commented
:+1: Approved

2020-12-04 15:19 UTC, ellykits approved these changes

2020-12-04 15:58 UTC, merged