Adds the Compliance Feature on the Child Register Page
OpenSRP/opensrp-client-child pull request #232
Opened 2021-02-25 17:53 UTC by paulinembabu

See issue: https://github.com/OpenSRP/opensrp-client-emmunize-malawi/issues/9

2021-03-04 09:00 UTC, bennsimon requested changes

2021-03-04 09:00 UTC, bennsimon commented on opensrp-child/src/main/java/org/smartregister/child/task/VaccinationAsyncTask.java
> +            String name = alert.visitCode().trim().replace(" ", "").toLowerCase();
Check for null here on ` alert.visitCode()`

2021-03-04 09:00 UTC, bennsimon commented on opensrp-child/src/main/java/org/smartregister/child/task/VaccinationAsyncTask.java
> +            complianceCheck.setImageResource(R.drawable.ic_yelllow_flag);
typo here `ic_yelllow_flag`

2021-03-04 09:00 UTC, bennsimon commented on opensrp-child/src/main/res/layout/child_register_header.xml
> +    android:weightSum="13.4">
Will this design change affect other projects?

2021-03-05 07:19 UTC, paulinembabu commented on opensrp-child/src/main/java/org/smartregister/child/task/VaccinationAsyncTask.java
> +            String name = alert.visitCode().trim().replace(" ", "").toLowerCase();
done

2021-03-05 07:19 UTC, paulinembabu commented on opensrp-child/src/main/java/org/smartregister/child/task/VaccinationAsyncTask.java
> +            complianceCheck.setImageResource(R.drawable.ic_yelllow_flag);
Edited

2021-03-05 07:25 UTC, paulinembabu commented on opensrp-child/src/main/res/layout/child_register_header.xml
> +    android:weightSum="13.4">
Have Put the WeightSum to 10.6 and made sure that it's not affecting other Implementations

2021-03-05 09:43 UTC, bennsimon requested changes

2021-03-05 09:43 UTC, bennsimon commented on opensrp-child/src/main/java/org/smartregister/child/provider/ChildRegisterProvider.java
> +        if (ChildLibrary.getInstance().getProperties().hasProperty(Constants.PROPERTY.HOME_COMPLIANCE_ENABLED)) {
Is this necessary isnt the default from `ChildLibrary.getInstance().getProperties().getPropertyBoolean` `false`

2021-03-05 09:43 UTC, bennsimon commented on opensrp-child/src/main/java/org/smartregister/child/provider/ChildRegisterProvider.java
> +        if (ChildLibrary.getInstance().getProperties().hasProperty(ChildAppProperties.KEY.HOME_COMPLIANCE_ENABLED)) {
Is this necessary isnt the default from `ChildLibrary.getInstance().getProperties().getPropertyBoolean` `false`

2021-03-05 09:43 UTC, bennsimon commented on opensrp-child/src/main/java/org/smartregister/child/task/VaccinationAsyncTask.java
> +                String name = alert.visitCode().trim().replace(" ", "").toLowerCase();
Check for null on ` alert.visitCode()`

2021-03-05 09:43 UTC, bennsimon commented on opensrp-child/src/main/res/layout/child_register_header.xml
> +    android:weightSum="10.6">
Does this change affect other projects?

2021-03-05 09:43 UTC, bennsimon commented on opensrp-child/src/main/java/org/smartregister/child/util/ChildAppProperties.java
> +        public  static final String HOME_COMPLIANCE_ENABLED = "home.compliance.enabled";
kindly add some description in the ReadMe

2021-03-05 09:56 UTC, paulinembabu commented on opensrp-child/src/main/res/layout/child_register_header.xml
> +    android:weightSum="10.6">
No it doesn't

2021-03-05 10:30 UTC, paulinembabu commented on opensrp-child/src/main/java/org/smartregister/child/provider/ChildRegisterProvider.java
> +        if (ChildLibrary.getInstance().getProperties().hasProperty(Constants.PROPERTY.HOME_COMPLIANCE_ENABLED)) {
Yes, It is. This is the Check that is made to Show or Hide on the App. So yes the default is False but it changes on the app

2021-03-05 10:40 UTC, paulinembabu commented on opensrp-child/src/main/java/org/smartregister/child/provider/ChildRegisterProvider.java
> +        if (ChildLibrary.getInstance().getProperties().hasProperty(ChildAppProperties.KEY.HOME_COMPLIANCE_ENABLED)) {
Yes, It is. This is the Check that is made to Show or Hide on the App. So yes the default is False but it changes on the app

2021-03-05 16:02 UTC, bennsimon approved these changes

2021-03-05 16:07 UTC, merged